# Introduction to Pandas and Scikit-learn

This notebook introduces two important Python libraries:

- **Pandas** is used to load, inspect, select, filter, and summarise data.
- **Scikit-learn** is used to create and test a simple machine learning model.

The notebook uses the Iris flower dataset supplied in the file `iris_intro.csv`.

## Learning outcomes

By the end of this practical, a student should be able to:

- import Pandas and selected scikit-learn tools;
- load a CSV file into a DataFrame;
- inspect rows, columns, and data types;
- select and filter data;
- calculate simple summary statistics;
- separate features from a target;
- split data into training and test sets;
- train a basic classification model;
- make predictions and calculate accuracy.

## 1. Import the libraries

The conventional alias for Pandas is `pd`.

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

## 2. Load the CSV file

`pd.read_csv()` reads the CSV file and stores it in a Pandas DataFrame.

The CSV file should be stored in the same folder as this notebook.

In [2]:
df = pd.read_csv("iris_intro.csv")
df

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,species_id
0,5.1,3.5,1.4,0.2,setosa,0
1,4.9,3.0,1.4,0.2,setosa,0
2,4.7,3.2,1.3,0.2,setosa,0
3,4.6,3.1,1.5,0.2,setosa,0
4,5.0,3.6,1.4,0.2,setosa,0
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,2
146,6.3,2.5,5.0,1.9,virginica,2
147,6.5,3.0,5.2,2.0,virginica,2
148,6.2,3.4,5.4,2.3,virginica,2
149,5.9,3.0,5.1,1.8,virginica,2

## 3. View the first rows

`head()` displays the first five rows by default.

In [3]:
df.head()

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,species_id
0,5.1,3.5,1.4,0.2,setosa,0
1,4.9,3.0,1.4,0.2,setosa,0
2,4.7,3.2,1.3,0.2,setosa,0
3,4.6,3.1,1.5,0.2,setosa,0
4,5.0,3.6,1.4,0.2,setosa,0

## 4. Inspect the DataFrame

`info()` displays the column names, data types, and number of non-empty values.

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sepal_length_cm  150 non-null    float64
 1   sepal_width_cm   150 non-null    float64
 2   petal_length_cm  150 non-null    float64
 3   petal_width_cm   150 non-null    float64
 4   species          150 non-null    str
 5   species_id       150 non-null    int64
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

## 5. View summary statistics

`describe()` calculates useful statistics for numerical columns.

In [5]:
df.describe()

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species_id
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

## 6. Select one column

A single column can be selected using its name.

In [6]:
df["sepal_length_cm"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length_cm, Length: 150, dtype: float64

## 7. Select several columns

A list of column names can be used to select more than one column.

In [7]:
df[["sepal_length_cm", "petal_length_cm", "species"]]

     sepal_length_cm  petal_length_cm    species
0                5.1              1.4     setosa
1                4.9              1.4     setosa
2                4.7              1.3     setosa
3                4.6              1.5     setosa
4                5.0              1.4     setosa
..               ...              ...        ...
145              6.7              5.2  virginica
146              6.3              5.0  virginica
147              6.5              5.2  virginica
148              6.2              5.4  virginica
149              5.9              5.1  virginica

[150 rows x 3 columns]

## 8. Filter rows

The following code selects flowers with a petal length greater than 5 cm.

In [8]:
large_petals = df[df["petal_length_cm"] > 5]
large_petals.head()

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,species_id
83,6.0,2.7,5.1,1.6,versicolor,1
100,6.3,3.3,6.0,2.5,virginica,2
101,5.8,2.7,5.1,1.9,virginica,2
102,7.1,3.0,5.9,2.1,virginica,2
103,6.3,2.9,5.6,1.8,virginica,2

## 9. Calculate a mean

The following code calculates the mean sepal length.

In [9]:
mean_sepal_length = df["sepal_length_cm"].mean()
print(f"Mean sepal length: {mean_sepal_length:.2f} cm")

Mean sepal length: 5.84 cm

## 10. Count categories

`value_counts()` counts the number of rows for each flower species.

In [10]:
df["species"].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

## 11. Create a new column

A new column can be created from existing columns.

In [11]:
df["sepal_area"] = df["sepal_length_cm"] * df["sepal_width_cm"]
df.head()

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,species_id,sepal_area
0,5.1,3.5,1.4,0.2,setosa,0,17.85
1,4.9,3.0,1.4,0.2,setosa,0,14.70
2,4.7,3.2,1.3,0.2,setosa,0,15.04
3,4.6,3.1,1.5,0.2,setosa,0,14.26
4,5.0,3.6,1.4,0.2,setosa,0,18.00

# Introduction to machine learning

The task is to predict a flower's species from four measurements.

The four measurement columns are called the **features**.

The `species_id` column is called the **target**.

## 12. Select the features and target

In [ ]:
feature_columns = [
    "sepal_length_cm",
    "sepal_width_cm",
    "petal_length_cm",
    "petal_width_cm",
]

X = df[feature_columns]
y = df["species_id"]

print("Feature data shape:", X.shape)
print("Target data shape:", y.shape)

## 13. Split the data

The training data is used to teach the model.

The test data is kept separate and used to evaluate the model.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y,
)

print("Training rows:", len(X_train))
print("Test rows:", len(X_test))

## 14. Create and train a decision tree

A decision tree is a simple classification model.

`random_state` makes the result reproducible.

In [ ]:
model = DecisionTreeClassifier(
    max_depth=3,
    random_state=42,
)

model.fit(X_train, y_train)

## 15. Make predictions

In [ ]:
predictions = model.predict(X_test)
predictions[:10]

## 16. Measure accuracy

Accuracy is the proportion of correct predictions.

In [ ]:
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy:.2%}")

## 17. Compare actual and predicted values

In [ ]:
results = pd.DataFrame({
    "actual_species_id": y_test.to_numpy(),
    "predicted_species_id": predictions,
})

results.head(10)

## 18. Predict one new flower

The new flower must contain the same four measurements, in the same order as the training data.

In [ ]:
new_flower = pd.DataFrame(
    [[5.1, 3.5, 1.4, 0.2]],
    columns=feature_columns,
)

predicted_id = model.predict(new_flower)[0]

species_names = {
    0: "setosa",
    1: "versicolor",
    2: "virginica",
}

print("Predicted species:", species_names[predicted_id])

# Exercises

1. Display the last five rows using `tail()`.
2. Calculate the average petal width.
3. Display flowers with a sepal width greater than 3.5 cm.
4. Create a column called `petal_area`.
5. Change the test size from `0.30` to `0.20` and compare the accuracy.
6. Change `max_depth` in the decision tree and observe the result.

In [ ]:
# Exercise workspace

# Example:
# df.tail()

## Optional challenge

Try a different classifier and compare its accuracy with the decision tree.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

knn_predictions = knn_model.predict(X_test)
knn_accuracy = accuracy_score(y_test, knn_predictions)

print(f"K-nearest neighbours accuracy: {knn_accuracy:.2%}")

## Summary

This notebook demonstrated a basic data science workflow:

1. load data from a CSV file;
2. inspect and summarise the data with Pandas;
3. select features and a target;
4. split the data into training and test sets;
5. train a scikit-learn model;
6. make predictions;
7. evaluate the model using accuracy.